### 문제 1
GET http://{{host}}/api/explore/v1/coordi/affordable

### 문제 2
GET http://{{host}}/api/explore/v1/coordi/affordable/brand

### 문제 3
GET http://{{host}}/api/explore/v1/coordi/category/%EC%83%81%EC%9D%98/price/range
